[workspace]
resolver = "3"
members = [
    "crates/vapoursynth-sys",
    "crates/vapoursynth-core",
]

[workspace.package]
edition = "2024"
rust-version = "1.85"
license = "MIT"
repository = "https://github.com/PlaneSight/vapoursynth-rust-webassembly"


[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
missing_docs = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
