[package]
name = "vapoursynth-wasm-host"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen.workspace = true
vapoursynth-core = { path = "../vapoursynth-core" }

[lints]
workspace = true
